apiVersion: v1
kind: Service
metadata:
name: login-service
labels:
  app: login
spec:
ports:
  - port: 80
    targetPort: 80
selector:
  app: login
type: LoadBalancer
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: login-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /login/(.*)
          backend:
            serviceName: login-service
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: JSVAR_DOCKERIMAGE
