apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: JSVAR_DOCKERIMAGE
#        livenessProbe:
#          httpGet:
#            path: /login/test.php
#            port: 80
#          initialDelaySeconds: 3
#          periodSeconds: 3
#        readinessProbe:
#          httpGet:
#            path: /login/test.php
#            port: 80
#          initialDelaySeconds: 3
#          periodSeconds: 3
#        ports:
#        - name: login
#          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: NodePort
  selector:
    app: login
  ports:
  - protocol: TCP
    port: 80
#    targetPort: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: login-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #kubernetes.io/ingress.class: gce
spec:
  rules:
  - http:
      paths:
        - path: /login/(.*)
          backend:
            serviceName: login-service
            servicePort: 80



